title:              'DMR2023'
email:              hsun@brandeis.edu
description:        The 4th International Workshop on Designing Meaning Representation
author:             
baseurl:            "/"
url:                "dmr2023.github.io"

# Social Profiles
twitter_username:   DMR2023
github_username:    DMR2023
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
